### ISSUE TITLE
Option to ignore years (or large numbers) in filenames, or a blacklist for domains

### ISSUE THREAD

**Issue by visua0** [KerfuffleV2/webextension-cancel-duplicate-downloads#1]
First of all, love the extension (in combination with "Save In…") and it's been working great.
I've had some issues where non-duplicate downloads kept getting canceled and it took me a while to realize this extension was the cause. The reason being the filenames ended with years such as `something (2020).pdf`.
It would be great if 4 digit numbers could be ignored. I doubt this would ever cause a problem since who would have 999 duplicates already?
An alternative (and more complicated) solution would be a customizable list of domains to ignore (through `DownloadItem.referrer` I guess).

**Comment by KerfuffleV2** [comment]
That's a good idea, and sorry about the unintended effects. I will look into this, but I'm bad at procrastinating. If you don't get a response in the next week, please poke me again.

**Comment by KerfuffleV2** [comment]
Well, after one million years... This finally should be resolved.

I'm very sorry, I accidentally marked this as read at some point and then forgot all about it. I made it so it should only trigger on up to two digits (who has 100 duplicates of a file?)

The new version should already be available if you check for addon updates.

**Comment by visua0** [comment]
Very nice, thanks!
